- Added test with compiled_krb files in eggs. - Upgraded to new version of ez_setup.py (version: 0.6c9) - Fixed a small documentation error in   logic_programming/rules/backward_chaining.txt (reported by Mr. Spoon) - This version passes ./testall.
--HG--
extra : convert_revision : svn%3A280a1989-90ef-4448-b869-2704929e1777/branches/release_1.0%40237

diff --git a/Test/testTest b/Test/testTest
--- a/Test/testTest
+++ b/Test/testTest
@@ -31,6 +31,23 @@ do
     fi
 done
 
+if ! $PYTHON setup.py --quiet bdist_egg
+then
+    echo "setup.py" >> $ERRORFILES
+    NUM_ERRORS=$(($NUM_ERRORS + 1))
+else
+    cd ..
+    if ! PYTHONPATH=`echo Test/dist/CanNotProve*.egg` $PYTHON doctest_file.py \
+           Test/CanNotProve/CanNotProve.tst2
+    then
+        echo "CanNotProve/CanNotProve.tst2" >> $ERRORFILES
+        NUM_ERRORS=$(($NUM_ERRORS + 1))
+    else
+        rm -rf Test/CanNotProve.egg-info Test/build Test/dist
+    fi
+    cd Test
+fi
+
 if [ $NUM_ERRORS -eq 0 ]
 then
     echo "No Errors!"
